# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 811, 551))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 460, 791, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Back_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Back_btn.setObjectName("Back_btn")
        self.horizontalLayout.addWidget(self.Back_btn)
        self.Upload_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Upload_btn.setObjectName("Upload_btn")
        self.horizontalLayout.addWidget(self.Upload_btn)
        self.Save_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Save_btn.setObjectName("Save_btn")
        self.horizontalLayout.addWidget(self.Save_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 791, 381))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Image1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Image1.setObjectName("Image1")
        self.horizontalLayout_2.addWidget(self.Image1)
        self.Image2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Image2.setObjectName("Image2")
        self.horizontalLayout_2.addWidget(self.Image2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Back_btn.setText(_translate("MainWindow", "Back"))
        self.Upload_btn.setText(_translate("MainWindow", "Upload Image"))
        self.Save_btn.setText(_translate("MainWindow", "Save"))
        self.Image1.setText(_translate("MainWindow", "TextLabel"))
        self.Image2.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
